services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "app.py"]

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: mealyuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mealydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
