services:
  - type: pserv
    name: mealydb
    env: postgres
    postgres:
      version: 15
    disk:
      name: mealy-db-disk
      sizeGB: 1
      mountPath: /var/lib/postgresql/data

  - type: web
    name: mealy-backend
    env: docker
    dockerContext: ./Backend
    dockerfilePath: ./Backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: mealydb
          property: connectionString
