services:
  - type: pserv
    name: mealydb
    env: postgres
    postgres:
      version: 15
    disk:
      name: mealy-db-disk
      sizeGB: 1
      mountPath: /var/lib/postgresql/data

  - type: web
    name: mealy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    preDeployCommand: alembic upgrade head
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: mealydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
