services:
  - type: web
    name: mealy-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: mealy-db
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_super_secret_key_here

databases:
  - name: mealy-db
    plan: free
