services:
  - type: web
    name: mealy-backend
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mealydb
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_very_secret_random_key

databases:
  - name: mealydb
    plan: free
