services:
  - type: pserv
    name: mealydb
    env: postgres
    postgres:
      version: 15
    disk:
      name: mealy-db-disk
      sizeGB: 1
      mountPath: /var/lib/postgresql/data

  - type: web
    name: mealy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT
    preDeployCommand: alembic upgrade head
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: mealydb
          property: connectionString
