"""Add Foreign Key to meals and user relationship

Revision ID: 5c49898b7ea5
Revises: b601b084c65c
Create Date: 2025-07-16 22:36:01.514106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c49898b7ea5'
down_revision = 'b601b084c65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caterer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['caterer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caterer_id')

    # ### end Alembic commands ###
