version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://mealyuser:mypassword@localhost/mealydb
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mealyuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mealydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
