"""Initial migration

Revision ID: b1e1e29fdd6a
Revises: 
Create Date: 2025-07-31 21:51:12.787799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1e29fdd6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('caterer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_meals_caterer_id')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint('menus_date_key', type_='unique')
        batch_op.create_unique_constraint('unique_menu_per_caterer_per_date', ['date', 'caterer_id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_instructions', sa.Text(), nullable=True))
        batch_op.drop_index('ix_orders_menu_item_id')
        batch_op.drop_index('ix_orders_user_id')
        batch_op.drop_constraint('orders_menu_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meals', ['meal_id'], ['id'])
        batch_op.drop_column('menu_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_menu_item_id_fkey', 'menu_items', ['menu_item_id'], ['id'])
        batch_op.create_index('ix_orders_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_orders_menu_item_id', ['menu_item_id'], unique=False)
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('meal_id')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint('unique_menu_per_caterer_per_date', type_='unique')
        batch_op.create_unique_constraint('menus_date_key', ['date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('ix_meals_caterer_id', ['caterer_id'], unique=False)
        batch_op.alter_column('caterer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('available')

    # ### end Alembic commands ###
